# **EXPERIMENT PYTHON**

### **Nama:** Lisya Apriliani

---

### **NIM:** 24060119120016

---

### **Data Besar (A)**

In [ ]:
help(len)
len?

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
L = [1,2,3]
L?
print(L)

[1, 2, 3]


In [ ]:
x = 4         #integer
x = 'empat'   #string

In [ ]:
import numpy
import numpy as np
numpy.__version__

'1.21.5'

In [ ]:
L = list(range(10))
print(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
type(L[0])
print(L[0])
print(L[1])
print(L[5])

0
1
5


In [ ]:
L2 = [str(c) for c in L]
print(L2)
type(L2[0])

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


str

In [ ]:
L3 = [True, '2', 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [ ]:
np.array([1, 4, 2, 5, 3])                 #membuat array dari list
np.array([1, 2, 3, 4], dtype = 'float32') #menentukan tipe data 

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
import numpy as np
np.random.seed(0)
x1 = np.random.randint(10, size=6) #satu dimensi
x2 = np.random.randint(10, size=(3, 4)) #dua dimensi
x3 = np.random.randint(10, size=(3, 4, 5)) #tiga dimensi
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [ ]:
print('x3 ndim: ', x3.ndim)
print('x3 shape: ', x3.shape)
print('x3 size: ', x3.size)
print(x3)
print('dtype: ', x3.dtype)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
dtype:  int64


In [ ]:
print(x1)
print(x1[0])
print(x3)
print(x3[0])
print(x3[0,0])

[5 0 3 3 7 9]
5
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
[[8 1 5 9 8]
 [9 4 3 0 3]
 [5 0 2 3 8]
 [1 3 3 3 7]]
[8 1 5 9 8]


In [ ]:
x = np.arange(10)
print(x)
print(x[:5]) #dari awal hingga elemen ke 5 
print(x[5:]) #mulai elemen ke 5
print(x[4:7]) #dari elemen ke 4 hingga elemen ke 7 
print(x[::2]) #semua elemen dari awal lompat 2
print(x[::-1]) #semua elemen dari belakang

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [ ]:
print(x2)
print(x2[:2, :3])  #baris awal hingga 2, kolom awal hingga 3
print(x2[:, 0])    #semua baris pada kolom 0
print(x2[0, :])    #baris ke 0

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[3 5 2]
 [7 6 8]]
[3 7 1]
[3 5 2 4]


In [ ]:
x = np.array([1, 2, 3])
y = np.array([6, 7, 8])
hrz = np.concatenate([x, y])
print(hrz)
vrt = np.array([x, [4, 5, 6]])
print(vrt)

[1 2 3 6 7 8]
[[1 2 3]
 [4 5 6]]


In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)
print(x3)

[1 2 3] [99 99] [3 2 1]
[3 2 1]


In [ ]:
grid = np.arange(16).reshape((4, 4))
atas, bawah = np.vsplit(grid, [2])
print(grid)
print(atas)
print(bawah)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
kiri, kanan = np.hsplit(grid, [2])
print(kiri)
print(kanan)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
